pages:
  image: node:20
  script:
    - |
      cat > .env <<EOF
      REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY
      REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN
      REACT_APP_FIREBASE_PROJECT_ID=$REACT_APP_FIREBASE_PROJECT_ID
      REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID
      REACT_APP_FIREBASE_APP_ID=$REACT_APP_FIREBASE_APP_ID
      REACT_APP_SOURCE_API_KEY=$REACT_APP_SOURCE_API_KEY
      REACT_APP_SOURCE_AUTH_DOMAIN=$REACT_APP_SOURCE_AUTH_DOMAIN
      REACT_APP_SOURCE_PROJECT_ID=$REACT_APP_SOURCE_PROJECT_ID
      REACT_APP_SOURCE_STORAGE_BUCKET=$REACT_APP_SOURCE_STORAGE_BUCKET
      REACT_APP_SOURCE_MESSAGING_SENDER_ID=$REACT_APP_SOURCE_MESSAGING_SENDER_ID
      REACT_APP_SOURCE_APP_ID=$REACT_APP_SOURCE_APP_ID
      EOF
    - npm install
    - npm run build
    - cp -r build public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - main
